In [56]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import graphviz

In [58]:
materiales = pd.read_csv('materiales.csv')
materiales

,name,usablegc,usablevc,density,porosity,Ri,ssa,specific
0,cc2s/cc2hg088,4.78,0.0157,0.312,0.84,15.71,4751,2.692
1,cc2s/cc2hj8cp,3.23,0.0145,0.433,0.60,5.70,5445,1.384
2,cc2s/cc2j6dpv,1.64,0.0122,0.728,0.32,4.65,3195,0.440
3,jlu-mof108/dupver_P1,1.63,0.0134,0.813,0.44,4.71,2885,0.541
4,jlu-mof108/heffef_P1_charged,1.82,0.0136,0.733,0.46,4.77,3335,0.627
...,...,...,...,...,...,...,...,...
100,MOF-selected-poro-dens-NU2100/voxzep_P1,0.32,0.0072,2.260,0.14,5.31,456,0.062
101,mrts/mrt1,0.35,0.0044,1.250,0.06,2.43,882,0.048
102,mrts/mrt2,2.19,0.0125,0.559,0.50,5.79,3752,0.893
103,mrts/mrt3,0.02,0.0004,1.685,0.00,1.68,124,0.000
104,mrts/mrt4,2.55,0.0143,0.547,0.48,5.38,3675,0.877

In [60]:
materiales['Class'] = None

In [62]:
materiales

,name,usablegc,usablevc,density,porosity,Ri,ssa,specific,Class
0,cc2s/cc2hg088,4.78,0.0157,0.312,0.84,15.71,4751,2.692,None
1,cc2s/cc2hj8cp,3.23,0.0145,0.433,0.60,5.70,5445,1.384,None
2,cc2s/cc2j6dpv,1.64,0.0122,0.728,0.32,4.65,3195,0.440,None
3,jlu-mof108/dupver_P1,1.63,0.0134,0.813,0.44,4.71,2885,0.541,None
4,jlu-mof108/heffef_P1_charged,1.82,0.0136,0.733,0.46,4.77,3335,0.627,None
...,...,...,...,...,...,...,...,...,...
100,MOF-selected-poro-dens-NU2100/voxzep_P1,0.32,0.0072,2.260,0.14,5.31,456,0.062,None
101,mrts/mrt1,0.35,0.0044,1.250,0.06,2.43,882,0.048,None
102,mrts/mrt2,2.19,0.0125,0.559,0.50,5.79,3752,0.893,None
103,mrts/mrt3,0.02,0.0004,1.685,0.00,1.68,124,0.000,None
104,mrts/mrt4,2.55,0.0143,0.547,0.48,5.38,3675,0.877,None

In [64]:
clave_valor = {"cc2s": 0, "jlu-": 1, "kezb": 2, "mof5": 3, "mof-": 4, "MOF-": 5, "mrts": 6}

In [66]:
pd.options.mode.copy_on_write = True

In [68]:
for idx in materiales.index:
   materiales.iloc[idx, -1] = clave_valor[materiales['name'][idx][0:4]]

In [70]:
materiales

,name,usablegc,usablevc,density,porosity,Ri,ssa,specific,Class
0,cc2s/cc2hg088,4.78,0.0157,0.312,0.84,15.71,4751,2.692,0
1,cc2s/cc2hj8cp,3.23,0.0145,0.433,0.60,5.70,5445,1.384,0
2,cc2s/cc2j6dpv,1.64,0.0122,0.728,0.32,4.65,3195,0.440,0
3,jlu-mof108/dupver_P1,1.63,0.0134,0.813,0.44,4.71,2885,0.541,1
4,jlu-mof108/heffef_P1_charged,1.82,0.0136,0.733,0.46,4.77,3335,0.627,1
...,...,...,...,...,...,...,...,...,...
100,MOF-selected-poro-dens-NU2100/voxzep_P1,0.32,0.0072,2.260,0.14,5.31,456,0.062,5
101,mrts/mrt1,0.35,0.0044,1.250,0.06,2.43,882,0.048,6
102,mrts/mrt2,2.19,0.0125,0.559,0.50,5.79,3752,0.893,6
103,mrts/mrt3,0.02,0.0004,1.685,0.00,1.68,124,0.000,6
104,mrts/mrt4,2.55,0.0143,0.547,0.48,5.38,3675,0.877,6

In [72]:
X=np.array(materiales.iloc[:, 1:-1])

In [74]:
y = np.array(materiales.iloc[:, -1], dtype=int)

In [76]:
tree = DecisionTreeClassifier()

In [78]:
tree.fit(X, y)

DecisionTreeClassifier()

In [104]:
export_graphviz(decision_tree=tree, out_file="tree.dot", feature_names=[materiales.columns[1:-1][i][1:-1] for i in range(7)])

In [106]:
! dot 'tree.dot' -Tpdf -o tree_logical.pdf

In [102]:
[materiales.columns[1:-1][i][1:-1] for i in range(7)]

['usableg', 'usablev', 'densit', 'porosit', 'R', 'ss', 'specifi']

In [113]:
np.mean(tree.predict(X) == y)

1.0

In [118]:
materiales['Class'].unique()

array([0, 1, 2, 3, 4, 5, 6], dtype=object)