In [1]:
import pandas as pd

In [8]:
materiales = pd.read_csv('materiales.csv')
materiales

,name,usablegc,usablevc,density,porosity,Ri,ssa,specific
0,cc2s/cc2hg088,4.78,0.0157,0.312,0.84,15.71,4751,2.692
1,cc2s/cc2hj8cp,3.23,0.0145,0.433,0.60,5.70,5445,1.384
2,cc2s/cc2j6dpv,1.64,0.0122,0.728,0.32,4.65,3195,0.440
3,jlu-mof108/dupver_P1,1.63,0.0134,0.813,0.44,4.71,2885,0.541
4,jlu-mof108/heffef_P1_charged,1.82,0.0136,0.733,0.46,4.77,3335,0.627
...,...,...,...,...,...,...,...,...
100,MOF-selected-poro-dens-NU2100/voxzep_P1,0.32,0.0072,2.260,0.14,5.31,456,0.062
101,mrts/mrt1,0.35,0.0044,1.250,0.06,2.43,882,0.048
102,mrts/mrt2,2.19,0.0125,0.559,0.50,5.79,3752,0.893
103,mrts/mrt3,0.02,0.0004,1.685,0.00,1.68,124,0.000
104,mrts/mrt4,2.55,0.0143,0.547,0.48,5.38,3675,0.877

In [10]:
materiales['Class'] = None

In [12]:
materiales

,name,usablegc,usablevc,density,porosity,Ri,ssa,specific,Class
0,cc2s/cc2hg088,4.78,0.0157,0.312,0.84,15.71,4751,2.692,None
1,cc2s/cc2hj8cp,3.23,0.0145,0.433,0.60,5.70,5445,1.384,None
2,cc2s/cc2j6dpv,1.64,0.0122,0.728,0.32,4.65,3195,0.440,None
3,jlu-mof108/dupver_P1,1.63,0.0134,0.813,0.44,4.71,2885,0.541,None
4,jlu-mof108/heffef_P1_charged,1.82,0.0136,0.733,0.46,4.77,3335,0.627,None
...,...,...,...,...,...,...,...,...,...
100,MOF-selected-poro-dens-NU2100/voxzep_P1,0.32,0.0072,2.260,0.14,5.31,456,0.062,None
101,mrts/mrt1,0.35,0.0044,1.250,0.06,2.43,882,0.048,None
102,mrts/mrt2,2.19,0.0125,0.559,0.50,5.79,3752,0.893,None
103,mrts/mrt3,0.02,0.0004,1.685,0.00,1.68,124,0.000,None
104,mrts/mrt4,2.55,0.0143,0.547,0.48,5.38,3675,0.877,None

In [36]:
materiales['name'][1]

'cc2s/cc2hj8cp'

In [50]:
clave_valor = {"cc2s": 0, "jlu-": 1, "kezb": 2, "mof5": 3, "mof-": 4, "MOF-": 5, "mrts": 6}

In [60]:
pd.options.mode.copy_on_write = True

In [62]:
for idx in materiales.index:
   materiales['Class'].iloc[idx] = clave_valor[materiales['name'][idx][0:4]]

/tmp/ipykernel_282766/1966638648.py:2: ChainedAssignmentError: A value is trying to be set on a copy of a DataFrame or Series through chained assignment.
When using the Copy-on-Write mode, such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy.

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  materiales['Class'].iloc[idx] = clave_valor[materiales['name'][idx][0:4]]